global.account;
global.EXPO_PUSH_TOKEN;
/* 
    PHP FILES IN LUXTRONIC/PUBLIC_HTML/MOBILE-API/ 
    ALL VARIABLES ARE DEFINED IN APP.JS
*/
global.API_DIRECTORY;
global.BOOK_PICKUP;
global.CANCEL_BOOKING;
global.CURRENT_BOOKINGS;
global.EDIT_PROFILE;
global.INSERT_BOOKING;
global.JOB_REQUEST;
global.JOB_REQUEST_RESPONSE;
global.PAST_BOOKINGS;
global.REGISTRATION;
global.SEARCH_BOOKINGS;
global.TECH_CURRENT_BOOKINGS;
global.TECH_CUSTOMERINFO_TICKETS;
global.TECH_PAST_BOOKINGS;
global.UPDATE_STATUS;
global.USER_LOGIN;
